In [1]:
print('hello world')

hello world

In [2]:
import os
from datetime import datetime, timedelta

base_dir = "/Users/galaxy/anti_codebase"
result_dir = "/Users/galaxy/anti_codebase/results/data_extract"
os.makedirs(result_dir, exist_ok=True)

# 1. 추출 기간 설정 (2026-01-01 ~ 2026-02-28)
start_date = datetime(2026, 1, 1)
end_limit = datetime(2026, 2, 28) + timedelta(days=1)

# 2. 파일 이름 동적 생성 (예: 0101_0228_gbike_revenue_extract.xlsx)
prefix = f"{start_date.strftime('%m%d')}_{end_limit.strftime('%m%d')}"
result_file = os.path.join(result_dir, f"{prefix}_gbike_revenue_extract.xlsx")

# 4일 단위로 기간 생성
date_ranges = []
current_start = start_date
while current_start < end_limit:
    current_end = min(current_start + timedelta(days=4), end_limit)
    date_ranges.append((current_start.strftime('%Y-%m-%d %H:%M:%S'), current_end.strftime('%Y-%m-%d %H:%M:%S')))
    current_start = current_end

In [3]:
date_ranges

[('2026-01-01 00:00:00', '2026-01-05 00:00:00'),
 ('2026-01-05 00:00:00', '2026-01-09 00:00:00'),
 ('2026-01-09 00:00:00', '2026-01-13 00:00:00'),
 ('2026-01-13 00:00:00', '2026-01-17 00:00:00'),
 ('2026-01-17 00:00:00', '2026-01-21 00:00:00'),
 ('2026-01-21 00:00:00', '2026-01-25 00:00:00'),
 ('2026-01-25 00:00:00', '2026-01-29 00:00:00'),
 ('2026-01-29 00:00:00', '2026-02-02 00:00:00'),
 ('2026-02-02 00:00:00', '2026-02-06 00:00:00'),
 ('2026-02-06 00:00:00', '2026-02-10 00:00:00'),
 ('2026-02-10 00:00:00', '2026-02-14 00:00:00'),
 ('2026-02-14 00:00:00', '2026-02-18 00:00:00'),
 ('2026-02-18 00:00:00', '2026-02-22 00:00:00'),
 ('2026-02-22 00:00:00', '2026-02-26 00:00:00'),
 ('2026-02-26 00:00:00', '2026-03-01 00:00:00')]

In [ ]:
from tqdm.auto import tqdm

bar = tqdm(range(1000))
for i in bar:
    bar.set_description(f'현재 숫자: {i}')

In [9]:
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine
import urllib.parse
import os
import sys
from datetime import datetime, timedelta

file_name = 'data_extract.csv'
# 1. 추출 기간 설정 (2026-01-01 ~ 2026-02-28)
start_date = datetime(2025, 1, 1)
end_limit = datetime(2025, 12, 31) + timedelta(days=1)

def get_engine():
    host = 'live.st.rds.gbility.io'
    user = 'gbikemarketing'
    password = urllib.parse.quote_plus('gbikemkt0514$@#!')
    port = 3306
    database = 'gbike'
    try:
        engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")
        return engine
    except Exception as e:
        print(f"Engine creation failed: {e}")
        sys.exit(1)

def main(file_name,start_date,end_limit):
    base_dir = "/Users/galaxy/anti_codebase"
    result_dir = "/Users/galaxy/anti_codebase/results/data_extract"
    os.makedirs(result_dir, exist_ok=True)


    # 2. 파일 이름 동적 생성 (예: 0101_0228_gbike_revenue_extract.xlsx)
    prefix = f"{start_date.strftime('%m%d')}_{end_limit.strftime('%m%d')}"
    result_file = os.path.join(result_dir, f"{prefix}_{file_name}.csv")

    engine = get_engine()


    query = f"""
    select o.user_id,o.from_api,count(o.order_id) as ord_cnt
    from gbike.rich_orders o
    where 1=1
    AND o.add_time >= UNIX_TIMESTAMP('{start_date}') - 32400
    AND o.add_time < UNIX_TIMESTAMP('{end_limit}') - 32400
    and o.order_state = 2
    group by o.user_id, o.from_api
    """
    with engine.connect() as connection:
        df = pd.read_sql(query, connection)
    df.to_excel(result_file, index=False, engine='openpyxl')
    print(f"Final file saved: {result_file} (Total: {len(df)} rows)")

if __name__ == "__main__":
    main(file_name,start_date,end_limit)

KeyboardInterrupt:

In [2]:
%%sql
describe gbike.rich_orders;

,Field,Type,Null,Key,Default,Extra
0,order_id,int,NO,PRI,NaN,auto_increment
1,order_sn,bigint,NO,MUL,NaN,NaN
2,user_id,int,NO,MUL,NaN,NaN
3,lock_sn,varchar(20),NO,MUL,NaN,NaN
4,cooperator_id,int,NO,NaN,0,NaN
...,...,...,...,...,...,...
69,uuid,binary(16),YES,MUL,"uuid_to_bin(uuid(),true)",DEFAULT_GENERATED
70,towing_fee,"decimal(10,0)",YES,NaN,0,NaN
71,refund_towing_fee,"decimal(10,0)",YES,NaN,0,NaN
72,service_key,varchar(20),YES,NaN,NaN,NaN
73,host_order_id,int,YES,NaN,NaN,NaN

In [7]:
#!/bin/python3

import math
import os
import random
import re
import sys

def is_odd(number: int) -> bool:
    return number % 2 != 0

def is_inclusive_range(number: int,start: int, end: int) -> bool:
    return start <= number <= end

def eval_weird_numbers(n: int) -> bool:
    if is_odd(n):
        return 'Weird'

    if is_inclusive_range(n, 2, 5):
        return 'Not Weird'

    if is_inclusive_range(n, 6, 20):
        return 'Weird'

    if n > 20:
        return 'Not Weird'

if __name__ == '__main__':
    n = int(input().strip())

    result = eval_weird_numbers(n)
    print(result)

Weird

In [9]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())

    sm = a + b
    diff = b - a
    power = a * b

    print(sm)
    print(diff)
    print(power)

5
1
6

In [19]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())

    print(a/b)
    c = a/b
    print(int(c))

1.3333333333333333
1

In [20]:
if __name__ == '__main__':
    n = int(input())

    # Iterate through all non-negative integers less than n
    for i in range(n):
        # Print the square of the current integer
        print(i ** 2)

0
1
4

In [32]:
%%sql
with RECURSIVE numbers as (
    select 2 as num
    union all
    select num + 1
    from numbers
    where num < 1000
)
select group_concat(num separator '&') as prime_list
from numbers n1
where not EXISTS (
    select 1
    from numbers n2
    where n2.num < n1.num
    and n1.num % n2.num = 0
);

                                          prime_list
0  2&3&5&7&11&13&17&19&23&29&31&37&41&43&47&53&59...

In [33]:
%%sql
WITH RECURSIVE numbers AS (
  SELECT 2 AS n
  UNION ALL
  SELECT 1+n FROM numbers WHERE n<1000
), Primes AS(
   SELECT n
   FROM numbers
   WHERE NOT EXISTS(
         SELECT n2.n
           FROM numbers AS n2
          WHERE n2.n > 1
            AND n2.n <= SQRT(numbers.n)
            AND numbers.n % n2.n = 0
   )
)
SELECT GROUP_CONCAT(Primes.n SEPARATOR '&')
FROM Primes;

                GROUP_CONCAT(Primes.n SEPARATOR '&')
0  2&3&5&7&11&13&17&19&23&29&31&37&41&43&47&53&59...